name: app_gerenciamento_cliente
description: "Desafio"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.20.0
  mask_text_input_formatter: ^2.9.0
  validators: ^3.0.0
  flutter_slidable: ^3.1.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11
  json_serializable: ^6.8.0

flutter:

  uses-material-design: true
